import React from 'react'

export default function Styles() {
  return (
    <head>
      <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
        crossorigin="anonymous"
      />
      <link
        href="./styles/style.css"
        rel="stylesheet"
      />
      <link
        href="./styles/cast.css"
        rel="stylesheet"
      />
      <link
        href="./styles/checkbox.css"
        rel="stylesheet"
      />
      <link
        href="./styles/details.css"
        rel="stylesheet"
      />{' '}
      <link
        href="./styles/discussion.css"
        rel="stylesheet"
      />
      <link
        href="./styles/dropdown.css"
        rel="stylesheet"
      />
      <link
        href="./styles/find.css"
        rel="stylesheet"
      />
      <link
        href="./styles/footer.css"
        rel="stylesheet"
      />
      <link
        href="./styles/game.css"
        rel="stylesheet"
      />
      <link
        href="./styles/lists.css"
        rel="stylesheet"
      />
      <link
        href="./styles/login.css"
        rel="stylesheet"
      />
      <link
        href="./styles/modal.css"
        rel="stylesheet"
      />
      <link
        href="./styles/navbar.css"
        rel="stylesheet"
      />
      <link
        href="./styles/popup.css"
        rel="stylesheet"
      />
      <link
        href="./styles/profile-icon.css"
        rel="stylesheet"
      />
      <link
        href="./styles/review.css"
        rel="stylesheet"
      />
      <link
        href="./styles/switchable.css"
        rel="stylesheet"
      />
      <link
        href="./styles/textInputcss"
        rel="stylesheet"
      />
      <link
        href="./styles/user.css"
        rel="stylesheet"
      />
      <link
        href="./styles/year-slider.css"
        rel="stylesheet"
      />
    </head>
  )
}
